"""empty message

Revision ID: 1f914cdf1566
Revises: 4715982d3abb
Create Date: 2022-04-24 17:31:41.265914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f914cdf1566'
down_revision = '4715982d3abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wenjuan_exts', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wenjuan_exts', 'create_time')
    # ### end Alembic commands ###
