"""empty message

Revision ID: 2161525a9f10
Revises: 
Create Date: 2022-04-23 10:22:45.470488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2161525a9f10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wenjuan_answer', sa.Column('total_score', sa.Integer(), nullable=True))
    op.add_column('wenjuan_answer', sa.Column('level', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wenjuan_answer', 'level')
    op.drop_column('wenjuan_answer', 'total_score')
    # ### end Alembic commands ###
