"""empty message

Revision ID: 4715982d3abb
Revises: cb832c448439
Create Date: 2022-04-23 12:34:00.318336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4715982d3abb'
down_revision = 'cb832c448439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wenjuan_answer', sa.Column('test_times', sa.Integer(), nullable=True))
    op.add_column('wenjuan_exts', sa.Column('test_times', sa.Integer(), nullable=True))
    op.drop_column('wenjuan_exts', 'create_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wenjuan_exts', sa.Column('create_time', mysql.DATETIME(), nullable=True))
    op.drop_column('wenjuan_exts', 'test_times')
    op.drop_column('wenjuan_answer', 'test_times')
    # ### end Alembic commands ###
