"""empty message

Revision ID: 87c2880a0c90
Revises: b1f173b38c8b
Create Date: 2022-05-08 20:44:37.191308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87c2880a0c90'
down_revision = 'b1f173b38c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captcha', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.drop_column('email_captcha', 'creat_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_captcha', sa.Column('creat_time', mysql.DATETIME(), nullable=True))
    op.drop_column('email_captcha', 'create_time')
    # ### end Alembic commands ###
