"""empty message

Revision ID: 9b75c3d71091
Revises: 8aaae6e8cd39
Create Date: 2022-05-05 19:42:22.027271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b75c3d71091'
down_revision = '8aaae6e8cd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_user_exts', sa.Column('report_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_user_exts', 'report_base64')
    # ### end Alembic commands ###
