"""empty message

Revision ID: b1f173b38c8b
Revises: 9b75c3d71091
Create Date: 2022-05-05 19:46:09.574731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1f173b38c8b'
down_revision = '9b75c3d71091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_user_exts', 'report_base64')
    op.add_column('wenjuan_exts', sa.Column('report_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wenjuan_exts', 'report_base64')
    op.add_column('student_user_exts', sa.Column('report_base64', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
