"""empty message

Revision ID: cb832c448439
Revises: 2161525a9f10
Create Date: 2022-04-23 10:25:36.116332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb832c448439'
down_revision = '2161525a9f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wenjuan_exts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('wenjuan_name', sa.String(length=200), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('wenjuan_answer', 'level')
    op.drop_column('wenjuan_answer', 'total_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wenjuan_answer', sa.Column('total_score', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('wenjuan_answer', sa.Column('level', mysql.VARCHAR(length=200), nullable=False))
    op.drop_table('wenjuan_exts')
    # ### end Alembic commands ###
